spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_identity?characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Kalamaja123
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1

flyway:
  user: root
  password: Kalamaja123
  datasource:
    url: ${spring.datasource.url}
    username: ${flyway.user}
    password: ${flyway.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    initialize: false
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1

escrow:
  encryption:
    password: Change-This-On-Production
